core/urls.py
from django.urls import path

from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

departamentos/urls.py
from django.urls import path

from .views import (DepartamentoCreate, DepartamentoDelete, DepartamentoEdit,
                    DepartamentoList)

app_name = 'departamentos'

urlpatterns = [
    path('list/', DepartamentoList.as_view(), name='list'),
    path('novo/', DepartamentoCreate.as_view(), name='create'),
    path('editar/<int:pk>/', DepartamentoEdit.as_view(), name='update'),
    path('delete/<int:pk>/', DepartamentoDelete.as_view(), name='delete'),
]

empresas/urls.py
from django.urls import path

from .views import EmpresaCreate, EmpresaEdit

app_name = 'empresas'

urlpatterns = [
    path('novo/', EmpresaCreate.as_view(), name='create_empresa'),
    path('editar/<int:pk>/', EmpresaEdit.as_view(), name='edit_empresa'),
]

funcionarios/urls.py
from django.urls import path

from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioCreate

app_name = 'funcionarios'

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list'),
    path('novo/', FuncionarioCreate.as_view(), name='create'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('documentos/', include('documentos.urls')),
    path('empresa/', include('empresas.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registro_hora_extra/urls.py
from django.urls import path
from .views import HoraExtraList, HoraExtraEdit, HoraExtraDelete, HoraExtraCreate

app_name = 'registro_hora_extra'

urlpatterns = [
    path('', HoraExtraList.as_view(), name='list'),
    path('editar/<int:pk>/', HoraExtraEdit.as_view(), name='update'),
    path('delete/<int:pk>/', HoraExtraDelete.as_view(), name='delete'),
    path('novo/',HoraExtraCreate.as_view(), name='create'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def home(request):
    data = {}
    data['usuario'] = request.user
    return render(request, 'core/index.html', data)

core/templates/core/index.html
{% extends 'base.html' %}

{% block main %}
<h1>Olá, {{ usuario.funcionario.nome }} </h1>
    {% if usuario.funcionario.empresa %}
        <p>
            Você pertence a seguinte empresa: 
            {{ usuario.funcionario.empresa.nome }}
        </p>
        <p>
            <a href="{% url 'empresas:edit_empresa' usuario.funcionario.empresa.id %}">
                Clique aqui para editar sua empresa
            </a>
        </p>
        <p>
            <a href="{% url 'logout' %}">
                Clique aqui para fazer logout
            </a>
        </p>
        <p>
            <a href="{% url 'funcionarios:list' %}">Gerenciar Funcionários</a>
        </p>
        <p>
            <a href="{% url 'departamentos:list' %}">Gerenciar Departamentos</a>
        </p>
        <p><a href="{% url 'registro_hora_extra:list' %}">Gerenciar banco de horas</a></p>
        {% else %}
        <a href="{% url 'empresas:create_empresa' %}">Criar empresa</a>
    {% endif %}
{% endblock main %}