core/urls.py
from django.urls import path

from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

documentos/urls.py
from django.urls import path

from .views import DocumentoCreate

app_name = 'documentos'

urlpatterns = [
    path('novo/<int:funcionario_id>/', DocumentoCreate.as_view(), name='create'),
]

funcionarios/urls.py
from django.urls import path

from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioCreate

app_name = 'funcionarios'

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list'),
    path('novo/', FuncionarioCreate.as_view(), name='create'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('documentos/', include('documentos.urls')),
    path('empresa/', include('empresas.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documentos/models.py
from django.db import models
from django.urls import reverse
from funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')
    
    def get_absolute_url(self, *args):
        return reverse('funcionarios:update', args=[self.pertence.id])
    
    def __str__(self):
        return self.descricao

funcionarios/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from departamentos.models import Departamento
from empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100, help_text="Nome do funcionário")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse('funcionarios:list')
    
    def __str__(self):
        return self.nome

funcionarios/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .models import Funcionario


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Funcionario.objects.filter(empresa=empresa_logada)
        return queryset
    
class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos',]
    
class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('funcionarios:list')
    
class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']
    
    def form_valid(self, form):
        funcionario = form.save(commit=False)
        funcionario.empresa = self.request.user.funcionario.empresa
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)

funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

<h1>Delete</h1>

<form method="POST">
    <h3>Você está certo que quer deletar {{ funcionario }} </h3>
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">
        Confirmar
    </button>

</form>

{% endblock main %}

funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

<h1>Edit</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-success">Salvar</button>
</form>

<a href="{% url 'documentos:create' object.pk %}" class="btn btn-success">
    Adicionar documento
</a>

{% for documento in object.documento_set.all %}
    <br />
    <a href="{{ documento.arquivo.url }}">{{ documento }}</a>
{% endfor %}

{% endblock main %}

funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}

    {% for funcionario in object_list %}
        <a href="{% url 'funcionarios:update' funcionario.id %}">
            {{ funcionario.nome }}
        </a>
        <a href="{% url 'funcionarios:delete' funcionario.id %}">
            Deletar
        </a>
    {% endfor %}
    <a href="{% url 'funcionarios:create' %}" class="btn btn-info">
        Novo funcionário
    </a>
{% endblock main %}