core/urls.py
from django.urls import path

from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('documentos/', include('documentos.urls')),
    path('empresa/', include('empresas.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registro_hora_extra/urls.py
from django.urls import path
from .views import HoraExtraList, HoraExtraEdit, HoraExtraDelete, HoraExtraCreate

app_name = 'registro_hora_extra'

urlpatterns = [
    path('', HoraExtraList.as_view(), name='list'),
    path('editar/<int:pk>/', HoraExtraEdit.as_view(), name='update'),
    path('delete/<int:pk>/', HoraExtraDelete.as_view(), name='delete'),
    path('novo/',HoraExtraCreate.as_view(), name='create'),
]

registro_hora_extra/models.py
from django.db import models
from django.urls import reverse
from funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    
    def get_absolute_url(self):
        return reverse('registro_hora_extra:update', args=[self.id])
    
    def __str__(self):
        return self.motivo

registro_hora_extra/forms.py
from django.forms import ModelForm
from .models import RegistroHoraExtra
from funcionarios.models import Funcionario


class RegistroHoraExtraForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(RegistroHoraExtraForm, self).__init__(*args, **kwargs)
        self.fields['funcionario'].queryset = Funcionario.objects.filter(
            empresa=user.funcionario.empresa
        )
        
        
    class Meta:
        model = RegistroHoraExtra
        fields = ['motivo', 'funcionario', 'horas']

registro_hora_extra/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import RegistroHoraExtraForm
from .models import RegistroHoraExtra


class HoraExtraList(ListView):
    model = RegistroHoraExtra
    
    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = RegistroHoraExtra.objects.filter(funcionario__empresa=empresa_logada)
        return queryset
    
    
class HoraExtraEdit(UpdateView):
    model = RegistroHoraExtra
    form_class = RegistroHoraExtraForm
    
    def get_form_kwargs(self):
        kwargs = super(HoraExtraCreate, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    

class HoraExtraDelete(DeleteView):
    model = RegistroHoraExtra
    success_url = reverse_lazy('registro_hora_extra:list')
    

class HoraExtraCreate(CreateView):
    model = RegistroHoraExtra
    form_class = RegistroHoraExtraForm
    
    def get_form_kwargs(self):
        kwargs = super(HoraExtraCreate, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

registro_hora_extra/templates/registro_hora_extra/registrohoraextra_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

<h1>Registro hora extra</h1>

<form method="POST">
    <h3>Você está certo que quer deletar: <br /> {{ object }} </h3>
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">
        Confirmar
    </button>

</form>

{% endblock main %}

registro_hora_extra/templates/registro_hora_extra/registrohoraextra_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

<h1>Edit</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-success">Salvar</button>
</form>

{% endblock main %}

registro_hora_extra/templates/registro_hora_extra/registrohoraextra_list.html
{% extends 'base.html' %}

{% block main %}

    <h1>Banco de horas</h1>
        {% for registro_he in object_list %}

        <a href="{% url 'registro_hora_extra:update' registro_he.id %}">
            {{ registro_he }}
        </a>

        <a href="{% url 'registro_hora_extra:delete' registro_he.id %}">
            Deletar
        </a>

    {% endfor %}

    {% if not object_list %}
        <h3>Não existe registro de hora extra no banco de dados</h3>
    {% endif %}

    <a href="{% url 'registro_hora_extra:create' %}" class="btn btn-info">
        Novo registro de hora extra
    </a> 

{% endblock main %}