core/urls.py
from django.urls import path

from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

departamentos/urls.py
from django.urls import path

from .views import (DepartamentoCreate, DepartamentoDelete, DepartamentoEdit,
                    DepartamentoList)

app_name = 'departamentos'

urlpatterns = [
    path('list/', DepartamentoList.as_view(), name='list'),
    path('novo/', DepartamentoCreate.as_view(), name='create'),
    path('editar/<int:pk>/', DepartamentoEdit.as_view(), name='update'),
    path('delete/<int:pk>/', DepartamentoDelete.as_view(), name='delete'),
]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('documentos/', include('documentos.urls')),
    path('empresa/', include('empresas.urls')),
    path('departamentos/', include('departamentos.urls')),
    path('horas-extras/', include('registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

departamentos/models.py
from django.db import models
from django.urls import reverse

from empresas.models import Empresa


class Departamento(models.Model):
    nome = models.CharField(max_length=100, help_text="Nome do departamento")
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT)
    
    def get_absolute_url(self):
        return reverse('departamentos:list')
    
    
    def __str__(self):
        return self.nome

departamentos/views.py
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Departamento


class DepartamentoList(ListView):
    model = Departamento
    
    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        queryset = Departamento.objects.filter(empresa=empresa_logada)
        return queryset

class DepartamentoCreate(CreateView):
    model = Departamento
    fields = ['nome',]
    
    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.funcionario.empresa
        departamento.save()
        return super(DepartamentoCreate,self).form_valid(form)


class DepartamentoDelete(DeleteView):
    model = Departamento
    success_url = reverse_lazy('departamentos:list')
    
    
class DepartamentoEdit(UpdateView):
    model = Departamento
    fields = ['nome', ]

departamentos/templates/departamentos/departamento_confirm_delete.html
{% extends 'base.html' %}

{% block main %}

<h1>Delete</h1>

<form method="POST">
    <h3>Você está certo que quer deletar o departamento: {{ departamento }}</h3>
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">
        Confirmar
    </button>
</form>

{% endblock main %}

departamentos/templates/departamentos/departamento_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}

<form method="POST">
    {% csrf_token %}
    {{ form |bootstrap }}
    <button type="submit" class="btn btn-success">
        Salvar
    </button>
</form>

{% endblock main %}

departamentos/templates/departamentos/departamento_list.html
{% extends 'base.html' %}

{% block main %}
    {% for departamento in object_list %}
        <a href="{% url 'departamentos:update' departamento.id %}">
            {{ departamento }}
        </a>
        <a href="{% url 'departamentos:delete' departamento.id %}">
            Delete
        </a>
        <br />
    {% endfor %}
    <a href="{% url 'departamentos:create' %}" class="btn btn-info">
        Novo departamento
    </a>
{% endblock main %}